---
#debug: true

#logging:
#  level:
#    net.runelite.cache.updater: debug
#    net.runelite.cache.client: debug

# Database
datasource:
  runelite-cache:
    jdbcUrl: jdbc:mysql://localhost/cache
    username: runelite
    password: runelite

rs:
  version: 223
  host: oldschool1.runescape.com

useNativeBzip: false