---
# Database
datasource:
  runelite-cache:
    jdbcUrl: jdbc:mysql://localhost/cache
    username: runelite
    password: runelite

# Minio client storage for cache
minio:
  endpoint: http://localhost:9000
  accesskey: admin
  secretkey: password
  bucket: runelite

rs:
  version: 214